### ISSUE TITLE
在互助中心问题内发表评论后，进入别的问题也能看到对应评论

### ISSUE THREAD

**Issue by Chlience** [BUAA-Bug-Not-Found/BanHang#212]
![图片](https://github.com/BUAA-Bug-Not-Found/BanHang/assets/22586392/519de627-14d0-4915-8843-e071aabc7b91)
![图片](https://github.com/BUAA-Bug-Not-Found/BanHang/assets/22586392/29006248-471f-4d90-b754-841ac89ef695)

如图，在图 1 中发布的评论点击右侧推荐问题，进入图 2，仍能看到上条评论

**Comment by Chlience** [comment]
并且头像也会继承上一条的头像

**Comment by BUAA-Wander** [comment]
并且这个时候点赞似乎会丢失，后面再进去就看不到了

**Comment by GYY000** [comment]
已经修复了qaq 似乎是没有重新渲染的问题
