### ISSUE TITLE
推荐问题列表较长时，靠下的推荐问题会因列表随滚轮向下滑动而看不到

### ISSUE THREAD

**Issue by BUAA-Wander** [BUAA-Bug-Not-Found/BanHang#216]
如图右下角所示

![afa54eeddbe8abdef96ba81755b859d](https://github.com/BUAA-Bug-Not-Found/BanHang/assets/59788931/368de4da-7469-4686-9bb6-c7d7e517c1a7)

**Comment by GYY000** [comment]
已经修复，感谢提出
