### ISSUE TITLE
互助中心发布问题上传视频失败

### ISSUE THREAD

**Issue by BUAA-Wander** [BUAA-Bug-Not-Found/BanHang#217]
如图，在使用上传视频功能时，我尝试上传一个mp4格式的大小为1.6MB的视频，但发布问题之后并没有看到上传的视频
![image](https://github.com/BUAA-Bug-Not-Found/BanHang/assets/59788931/dd1f23a5-9e15-4c8d-a78f-fb44ef449bdc)

**Comment by BUAA-Wander** [comment]
上传图片似乎也有类似的问题

**Comment by Chlience** [comment]
不再支持富文本编辑器视频的上传
