### ISSUE TITLE
内容审核

### ISSUE THREAD

**Issue by wsjdsg** [BUAA-Bug-Not-Found/BanHang#297]
利用宏墚的内容审核接口在发帖和评论时时进行内容审核，如果不合规需要进行警告提示

**Comment by wsjdsg** [comment]
@Chlience @GYY000 @Argithun @cpython-java 尽快测试一下审核接口

**Comment by Chlience** [comment]
#336 #346

**Comment by Argithun** [comment]
匿名帖、互助区、个人中心
